# Generated by Django 6.0.7 on 2026-07-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_venue_name_city'),
        ),
    ]
