# Generated by Django 6.0.7 on 2026-07-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10)),
                ('seat_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.section')),
            ],
            options={
                'ordering': ['row', 'seat_number'],
                'constraints': [models.UniqueConstraint(fields=('section', 'row', 'seat_number'), name='unique_seat_per_section')],
            },
        ),
    ]
