# Generated by Django 6.0.7 on 2026-07-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('venues', '0004_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sections', to='events.event')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sections', to='venues.section')),
            ],
            options={
                'ordering': ['section__display_order'],
                'constraints': [models.UniqueConstraint(fields=('event', 'section'), name='unique_section_per_event')],
            },
        ),
    ]
